### ISSUE TITLE
Weights removed?

### ISSUE THREAD

**Issue by krummrey** [radekosmulski/yolo_open_images#3]
The actual 250mb weights file doesn't get cloned only the meta data:

> version https://git-lfs.github.com/spec/v1
oid sha256:ff64e5f3cc1446b4badf0af25f93ac8f7982de0191b8f4df9423d2ba57b173bf
size 261256344

Oh, just found it...

> This repository is over its data quota. Purchase more data packs to restore access.

Maybe someone can share it via bit torrent or some other file hoster.

**Comment by radekosmulski** [comment]
Please try downloading from bitbucket - it does not have this limitation. Here is the [link](https://bitbucket.org/dreamwalkerrr/yolo_open_images/src/master/) to the repo. I'll add this piece of information to the readme.
