### ISSUE TITLE
Correct annotations.

### ISSUE THREAD

**Issue by dreambit** [radekosmulski/yolo_open_images#4]
@radekosmulski Hi

Have you modified annotations by hand or just left them as is?

There are a lot of images in this dataset like 
![image](https://user-images.githubusercontent.com/1479661/54269328-3c3fd680-458e-11e9-90ef-13b486f74c87.png)
![image](https://user-images.githubusercontent.com/1479661/54269340-41048a80-458e-11e9-9ceb-bd0d5209d5a7.png)

person class is not selected and this can degrade the accuracy.

Thanks

**Comment by radekosmulski** [comment]
I have not made any changes to the labels

**Comment by Rajasekhar06** [comment]
I think you are using we explore dataset feature OID website, there if you select only single class bounding boxes then it will show for single class @dreambit  un check that to get multi class bounding boxes
