### ISSUE TITLE
backup?

### ISSUE THREAD

**Issue by eliwilner** [radekosmulski/yolo_open_images#6]
Hi,

Trying to use your weights but it seems that the *.backup is not there...

**Comment by radekosmulski** [comment]
Hi! It has been a long while since I had anything to do with this to be honest.... I am thinking maybe I just used a wrong file name in the command? Maybe it should be `yolov3-spp_final.weights` instead?

Could you please let me know if this works for you so that I can update the readme?

**Comment by eliwilner** [comment]
Hi. 
Thanks for answering. I tried:
`./darknet detector test yolo.data yolov3-spp.cfg yolov3-spp_final.weights`
And when the model ask for an:
`Enter Image Path: `
and I give him data/dog.jpg (it is an image that is inside the darknet repo once you clone it)
it doesn't detect anything...
Any idea why?

**Comment by radekosmulski** [comment]
Sorry, no clue.
